name: Daily Update

on:
  repository_dispatch:
  push:        # Git Push 时触发编译(不要删除此行注释)
     branches: 
      - master
      - dev
      - gd
  schedule:
    - cron: '5 * * * *'  # 每2天凌晨00点55分执行任务（上海时区的UTC时间）
  workflow_dispatch:  # 允许手动触发工作流
  
env:
# 删除早期的 workflow 任务
   DELETE_OLD_WORKFLOW: true  
 
jobs:
  run_script:
    runs-on: ubuntu-latest  # 使用最新的Ubuntu运行器

    steps:
    - name: Checkout repository  # 检出代码库
      uses: actions/checkout@v3

    - name: Set up Python  # 设置Python环境
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'  # 使用Python 3.10

    - name: Cache dependencies  # 缓存pip依赖项
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install system dependencies  # 安装系统依赖
      run: |
        sudo apt-get update
        sudo apt-get install -y ffmpeg

    - name: Install Python dependencies  # 安装Python依赖
      run: |
        python -m pip install --upgrade pip
        pip install requests aiohttp

    - name: Run Python script  # 执行主脚本
      run: |
        python main.py
        
    #- name: Run Python script  # 执行测速脚本
     # run: |
        #python utils/speed_test.py

    - name: Commit and push if changed  # 如果有更改，则提交并推送
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add -A
        if ! git diff --staged --quiet; then
          git commit -m "Auto-update live files"
          git pull --rebase
          git push
        fi
    - name: 删除旧的工作流 (Delete old Workflow Runs)
      continue-on-error: true
      if: env.DELETE_OLD_WORKFLOW == 'true' && !cancelled()
      uses: Mattraks/delete-workflow-runs@v2
      with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          retain_days: 3
          keep_minimum_runs: 0
          body: |
    env:
      TZ: Asia/Shanghai  # 设置时区为上海

